---

- name: Install flocker dependencies
  apt: pkg={{ item }} state=latest
  with_items:
  - apt-transport-https
  - software-properties-common

- name: Add flocker repo
  apt_repository: repo='deb https://clusterhq-archive.s3.amazonaws.com/ubuntu/14.04/$(ARCH) /'
  become: true

- name: Add buildbot file
  copy: src=buildbot-700 dest=/etc/apt/preferences.d/buildbot-700
  become: true

- name: Install flocker-packages
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items:
  - clusterhq-flocker-cli
  - clusterhq-flocker-node
  - clusterhq-flocker-docker-plugin
  become: true

- name: Create flocker config directory
  file: path=/etc/flocker state=directory
  become: true

- find: paths=/etc/flocker/ patterns="*.*"
  register: dir_files

- name: generate flocker ca root certs
  command: chdir=/etc/flocker flocker-ca initialize dev-cluster
  when: dir_files.matched|int == 0
  become: true


