---

- name: Initiate swarm cluster
  shell: /usr/bin/docker swarm init --advertise-addr "{{ groups['master'][0] }}" --listen-addr "{{ groups['master'][0] }}":2377
  when:  "'{{ groups['master'][0] }}' == '{{ ansible_eth1['ipv4']['address'] }}'"
  become: true
  ignore_errors: true
  tags: [swarm-master]

- name: get cluster token
  shell: docker swarm join-token -q worker
  register: token
  become: true
  tags: [swarm-master]

- name: save cluster token
  set_fact: token="{{ token.stdout }}"
  tags: [swarm-master]
